version: '3.9'

networks:
  slotegrator_backend:
    driver: bridge

services:
  php-fpm-8:
    build:
      context: ./php8
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./..:/var/www
    networks:
      - slotegrator_backend
    ports:
      - "${PHP_PORT}:9000"
    depends_on:
      - mysql

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./../:/var/www
      - ./volumes/nginx/logs:/var/log/nginx
      - ./volumes/nginx/ssl:/etc/nginx/ssl
    networks:
      - slotegrator_backend
    ports:
      - 80:80
    depends_on:
      - php-fpm-8

  mysql:
    image: mysql:8.0
    restart: always
    volumes:
      - ./volumes/mysql:/var/lib/mysql
    networks:
      - slotegrator_backend
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
